[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pytent-docgen"
version = "0.0.0"
description = "Documentation generate from docstring for Pytent"
requires-python = ">=3.11"
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src/init"]