repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace

- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.8.3
  hooks:
    - id: commitizen
    - id: commitizen-branch
      stages: [commit-msg]

- repo: local
  hooks:
    - id: ruff
      name: formating
      entry: uvx ruff check . --fix
      language: python
      pass_filenames: false
      always_run: true

    - id: pyright
      name: typecheck
      entry: uvx pyright .
      language: python
      pass_filenames: false
      always_run: true

    - id: xenon
      name: complexity
      entry: uvx xenon .
      language: python
      pass_filenames: false
      always_run: true

    - id: uv-secure
      name: audit
      entry: uvx uv-secure .
      language: python
      pass_filenames: false
      always_run: true

    - id: pytest
      name: pytest
      entry: uvx pyright .
      language: python
      pass_filenames: false
      always_run: true