[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pytent-func"
version = "0.0.0"
description = "AWS function for Pytent"
requires-python = ">=3.11"
dependencies = [

]

[tool.hatch.build.targets.wheel]
packages = ["src/pytent.func"]