[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pytent-database"
version = "0.0.0"
description = "Database utilities for Pytent"
requires-python = ">=3.11"
dependencies = [
    "sqlalchemy>=2.0.0",
    "asyncpg>=0.28.0",
    "pytent-log",
    "pytent-error",
]

[tool.uv.sources]
pytent-log = { workspace = true }
pytent-error = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/pytent_db"]