[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pytent-deploy"
version = "0.0.0"
description = "Deployment Script for Pytent"
requires-python = ">=3.12"
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src/__init__"]