[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pytent-deploy"
version = "0.1.0"
description = "Deploy for Pytent"
requires-python = ">=3.11"
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src/init"]