name: CI

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Deps check
        run: uv lock --check

      - name: Format
        run: uv run ruff format

      - name: Lint
        run: uv run ruff check --output-format=json . > artifacts/ruff-output.json

      - name: Typecheck
        run: uv run pyright . --outputjson > artifacts/pyright-output.json 2>&1

      - name: Audit
        run: uv run --all-groups --with pip-audit pip-audit -l

      - name: Complexity Analysis
        run: uv run xenon ./ --paths-in-front > artifacts/complexity-report.json
        continue-on-error: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          path: artifacts
          retention-days: 30

  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - uses: ./.github/actions/setup

        - name: Build
          run: uv build --all-packages

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Test
        run: uv run pytest --cov=packages --cov-report=json:artifacts/coverage.json